# Generated by Django 3.0.6 on 2020-05-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_face'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('reg_type', models.CharField(max_length=100)),
                ('tickets', models.IntegerField()),
                ('photo_id', models.ImageField(upload_to='profile_image')),
                ('reg_number', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
