# Generated by Django 3.0.6 on 2020-05-31 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
