# Generated by Django 3.0.7 on 2020-06-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Face',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
