# Generated by Django 3.0.6 on 2020-06-07 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200607_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.Event'),
        ),
    ]
